server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

ratelimiterConfig:
  storageType: AEROSPIKE
  aerospikeConfig:
    hosts:
      - host: stg-aerospike102.phonepe.nm2
        port: 3000
    namespace: mercury
    maxConnectionsPerNode: 10
    timeout: 1000
    retries: 3
    sleepBetweenRetries: 5
    maxSocketIdle: 4140
    threadPoolSize: 512
  redisConfig:
    hosts:
      - host: stg-aerospike102.phonepe.nm2
        port: 3000
    namespace: redis