server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

ratelimiterConfig:
  dataBase: Aerospike