server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

storageConfigs:
  AEROSPIKE:
    type: AEROSPIKE
    hosts:
      - host: 127.0.0.1
        port: 3000
    namespace: docstore
    maxConnectionsPerNode: 10
    timeout: 1000
    retries: 3
    sleepBetweenRetries: 5
    maxSocketIdle: 4140
    threadPoolSize: 512
  REDIS:
    type: REDIS
      hosts:
          - host: 127.0.0.1
            port: 3000
      namespace: docstore
      maxConnectionsPerNode: 10
      timeout: 1000
      retries: 3
      sleepBetweenRetries: 5
      maxSocketIdle: 4140
      threadPoolSize: 512


